config/routes.rb
FetchAndStore::Application.routes.draw do
  root :to => "fetch#index"

  match '/you',           :to => 'fetch#show',    :as => :you
  match '/you/update',    :to => 'fetch#update',  :as => :you_update
  match '/you/track/',    :to => 'fetch#view',    :as => :you_track_view

  match '/you/buckets', :to => 'store#bucketlist', :as => :you_bucket_list
  match '/you/buckets/store', :to =>'store#store', :as => :you_bucket_store
  match '/you/buckets/create', :to =>'store#create', :as => :you_bucket_create
  match '/you/buckets/create/form', :to =>'store#form', :as => :you_bucket_form

  match '/soundcloud/connect',    :to => 'soundcloud#connect',    :as => :soundcloud_connect
  match '/soundcloud/connected',  :to => 'soundcloud#connected',  :as => :soundcloud_connected
  match '/soundcloud/disconnect', :to => 'soundcloud#disconnect', :as => :soundcloud_disconnect
end

app/models/amazon_user.rb
require 'yaml'

class AmazonUser

  @credentials = YAML.load_file('./config/credentials.yml')

  AMAZON_ACCESS_KEY_ID = @credentials['amazon']['access_key_id']
  AMAZON_SECRET_ACCESS_KEY = @credentials['amazon']['secret_access_key']

  AWS.config(
      :access_key_id => AMAZON_ACCESS_KEY_ID,
      :secret_access_key => AMAZON_SECRET_ACCESS_KEY )
  @s3 = AWS::S3.new

  def self.client()
    @s3
  end

end

app/models/user.rb
require 'yaml'

class User < ActiveRecord::Base
  # With great help from -> http://soundcloud.com/you/apps/connect-with-soundcloud-rails-demo
  @credentials = YAML.load_file('./config/credentials.yml')

  SOUNDCLOUD_CLIENT_ID     = @credentials['soundcloud']['client_id']
  SOUNDCLOUD_CLIENT_SECRET = @credentials['soundcloud']['client_secret']

  attr_accessible :soundcloud_access_token, :soundcloud_expires_at, :soundcloud_refresh_token, :soundcloud_user_id, :soundcloud_username, :photo_attributes

  def self.soundcloud_client(options={})
    options = {
      :client_id     => SOUNDCLOUD_CLIENT_ID,
      :client_secret => SOUNDCLOUD_CLIENT_SECRET,
    }.merge(options)

    Soundcloud.new(options)
  end
  
  
  def soundcloud_client(options={})
    options= {
      :expires_at    => soundcloud_expires_at,
      :access_token  => soundcloud_access_token,
      :refresh_token => soundcloud_refresh_token
    }.merge(options)
    
    client = self.class.soundcloud_client(options)
    
    # define a callback for successful token exchanges
    # this will make sure that new access_tokens are persisted once an existing 
    # access_token expired and a new one was retrieved from the soundcloud api
    client.on_exchange_token do
      self.update_attributes!({
        :soundcloud_access_token  => client.access_token,
        :soundcloud_refresh_token => client.refresh_token,
        :soundcloud_expires_at    => client.expires_at,
      })
    end
    
    client
  end

  def get_client_id
    SOUNDCLOUD_CLIENT_ID
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :login_from_session

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user
  end

  def login_as(user)
    @current_user = user
    session[:current_user_id] = user.try(:id)
  end

  def login_from_session
    @current_user = User.find_by_id(session[:current_user_id])
  end
end

app/controllers/fetch_controller.rb
class FetchController < ApplicationController
  def index
  end

  def show
    @tracks = current_user.soundcloud_client.get("/me/tracks", :limit => 5)
    @me     = current_user.soundcloud_client.get("/me")
  end

  def view
    #@track = current_user.soundcloud_client.get(params[:track_uri])
    @track = current_user.soundcloud_client.get('/resolve', :url => params[:track_url],:client_id=>current_user.get_client_id)
  end
end

app/controllers/soundcloud_controller.rb
class SoundcloudController < ApplicationController
  def connect
    redirect_to soundcloud_client.authorize_url(:display => "popup")
  end

  def connected
    if params[:error].nil?
      soundcloud_client.exchange_token(:code => params[:code])
      me = soundcloud_client.get("/me")

      login_as User.find_or_create_by_soundcloud_user_id({
        :soundcloud_user_id  => me.id,
        :soundcloud_username => me.username
      })

      current_user.update_attributes!({
        :soundcloud_access_token  => soundcloud_client.access_token,
        :soundcloud_refresh_token => soundcloud_client.refresh_token,
        :soundcloud_expires_at    => soundcloud_client.expires_at,
      })
    end
    render :layout => false
  end

  def disconnect
    login_as nil
    redirect_to root_path
  end
  
private

  def soundcloud_client
    return @soundcloud_client if @soundcloud_client
    @soundcloud_client = User.soundcloud_client(:redirect_uri  => soundcloud_connected_url)
  end

end

app/controllers/store_controller.rb
 require 'yaml'
 require 'open_uri_redirections'

class StoreController < ApplicationController

  def bucketlist
    @track_url = params[:track_url]
    @buckets = AmazonUser.client.buckets
  end

  def store
    @track = current_user.soundcloud_client.get('/resolve', :url => params[:track_url],:client_id => current_user.get_client_id)
    track_title = @track.title
    track_filename = "%s.aif" % track_title.to_s
    download_url = "%s?client_id=%s" % [@track.download_url,current_user.get_client_id.to_s]
    @bucket = AmazonUser.client.buckets[params[:bucket_name]]
    if not @bucket.objects[track_filename].exists?
      object = @bucket.objects.create(track_filename,"")
      open(download_url, allow_redirections: :all) do |read_file|
        object.write(read_file.read)
      end
      @stored = true
    else
      @stored = false
    end
  end

  def create
    @bucket_to_create = AmazonUser.client.buckets.create(params[:bucket_name].to_s)
    if @bucket.exists?
      @created = true
    else
      @created = false
    end
    redirect_to "you/bucket/create"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user
  end

  def logged_in?
    !!current_user
  end
end

app/views/fetch/index.html.haml
%p
  App that makes use of SoundCloud rails sdk.
%div{:class => "connect-with-soundcloud #{"connected" if logged_in?}"}
  - if not logged_in?
    = link_to "Connect With SoundCloud", soundcloud_connect_path, :class => "connect", :target =>"_blank"
  - else
    = link_to "Disconnect From SoundCloud", soundcloud_disconnect_path, :class => "disconnect"
    %span.current-user
      You are logged in as:
      %span.username= current_user.soundcloud_username if logged_in?
    %div{:class => "visible-when-logged-in#{"hidden" unless logged_in?}"}
      = link_to "Check out your profile infos", you_path

app/views/fetch/show.html.haml
.infos
  .details
    %b Your SoundCloud User Infos:
    %ul
      %li
        Username: #{@me.username}
      %li
        Fullname: #{@me.full_name}
      %li
        Location: #{@me.city}, #{@me.country}
  = image_tag(@me.avatar_url, :class => "avatar")
.description
  - form_tag you_update_path, :method => "post" do
    %b Description:
    %textarea{:name => "description"}= @me.description
    %input{:type => "submit", :value => "update"}/
    %span.warning this will change your SoundCloud profile description!
.tracks
  %b Your 5 latest tracks
  %ul
    - @tracks.each do |track|
      %li
      = link_to track.title, track.permalink_url
      - if track.downloadable
        = link_to "View to download", you_track_view_path(:track_url =>track.permalink_url)

app/views/fetch/view.html.haml
.track
   %h4 Requested Track
   .track_info
      %b #{@track.title}
      =button_to "Copy to S3",you_bucket_list_path(:track_url=>@track.permalink_url)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fetchandstore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Fetch and Store
    /= javascript_include_tag 'jquery-1.5.min', 'connect', 'application'
    /= csrf_meta_tag
    /%link{:rel => :stylesheet, :type => :"text/css", :href => "http://soundcloudfront.com/stylesheets/style.css"}
  %body
    .wrapper.container
      %h1.header Fetch and Store
      = yield

app/views/soundcloud/connected.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
    %title Connect with SoundCloud
  %body{:onload => "window.opener.SC.Connect.popupCallback(window)"}
    %b{:style => "width: 100%; text-align: center;"} Logged in. Close this window.

app/views/store/bucketlist.html.haml
.info
  .details
    %b Choose a bucket to store the file into.
    %ul
      - if not @buckets.nil?
        - @buckets.each do |bucket|
          %li
            = link_to bucket.name,you_bucket_store_path(:bucket_name=> bucket.name,:track_url=>@track_url)
    = link_to "Create new bucket and store.",you_bucket_form_path(:track_url=>@track_url)

app/views/store/create.html.haml
.create_info
  - if @created
    %b Created a Bucket named
      = link_to @bucket.name,you_bucket_store_path(:bucket_name=> @bucket_to_create.name,:track_url=>@track_url)
  - else
    %b Couldn't create a bucket.
      = link_to "<< Select an existing one.",you_bucket_list_path(:track_url=>@track_url)

app/views/store/form.html.haml
%html
  %body
    %form
      %input{:type=>"text",:name=>"bucket_name"}
      = button_to "Create bucket",you_bucket_create_path(:@track_url=>@track.permalink_url)

app/views/store/store.html.haml
- if @stored
  %b Stored file #{@track.title} to #{@bucket.name} bucket.
- else
  %b File #{@track.title} is already stored in #{@bucket.name} bucket.
= link_to "<< back to Track list",you_path